// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient("https://ytadpryffjruqjydxlsi.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0YWRwcnlmZmpydXFqeWR4bHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzE4ODcsImV4cCI6MjA3MjQ0Nzg4N30.4o562boRXWAttz3bG5ToK4cKHydCR8l4gya0j0tElnU", {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});